const GALERY = {
  placeholder: 'images/placeholder.jpg',
  layanan: {
    'desain-3d-interior': 'images/layanan/desain-3d-interior.jpg',
    'desain-3d-bangunan': 'images/layanan/desain-3d-bangunan.jpg',
    'bestek-gambar-kerja': 'images/layanan/bestek-gambar-kerja.jpg',
    'analisis-struktur': 'images/layanan/analisis-struktur.jpg',
    'estimasi-rab': 'images/layanan/estimasi-rab.jpg',
    'paket-all-in': 'images/layanan/paket-all-in.jpg',
  },
  portfolio: {
    'rumah-tropis-dago': 'images/portfolio/rumah-tropis-dago.jpg',
    'rumah-minimalis-buah-batu': 'images/portfolio/rumah-minimalis-buah-batu.jpg',
    'ded-villa-lembang': 'images/portfolio/ded-villa-lembang.jpg',
    'ded-rumah-cibiru': 'images/portfolio/ded-rumah-cibiru.jpg',
    'ded-ruko-soreang': 'images/portfolio/ded-ruko-soreang.jpg',
    'kos-gsh-antapani': 'images/portfolio/kos-gsh-antapani.jpg',
    'ruko-cimahi': 'images/portfolio/ruko-cimahi.jpg',
    'interior-master-suite': 'images/portfolio/interior-master-suite.jpg',
    'kitchen-set-japandi': 'images/portfolio/kitchen-set-japandi.jpg',
    'walk-in-closet': 'images/portfolio/walk-in-closet.jpg',
  },
  proses: [
    'images/proses/01-konsultasi.jpg',
    'images/proses/02-survey-lahan.jpg',
    'images/proses/03-konsep-3d.jpg',
    'images/proses/04-ded-struktur.jpg',
    'images/proses/05-rab-material.jpg',
    'images/proses/06-eksekusi.jpg',
    'images/proses/07-serah-terima.jpg',
  ],
  tim: {
    'FARIS MUHAMMAD SIDIQ': 'images/tim/muzqy zibran.jpg',
    'MUZQY ZIBRAN IBRANI': 'images/tim/MUZQY ZIBRAN IBRANI.jpeg',
    'SASKA DEWINTY': 'images/tim/siti musdalifah.jpg',
    'KINANTI RAMADHIANI SUGANDA': 'images/tim/syaeful hr.jpg',
    'SAFEER SAUMI': 'images/tim/safeer.jpeg',
    'FAHRI ARDIANSYAH': 'images/tim/fahri.jpeg',
  },
};
